name: run scraper.py

on:
  workflow_dispatch: # Allows you to manually trigger the scraper anytime from GitHub
  schedule:
    - cron: '3 * * * *' # Every hour, at 3 min past the hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        run: |
          python3 scraper.py # Runs directly at the root level for AL02
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Auto-update storm data [skip ci]" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main