name: run scraper.py

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI
  schedule:
    - cron: '3 * * * *' # Every hour, at 3 min past the hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute storm scrapers
        run: |
          python3 al02/scraper.py || true
          python3 al03/scraper.py || true
          python3 al04/scraper.py || true
          python3 al05/scraper.py || true
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-update active storm data (al02, al03, al04, al05)"
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main